export { default as AboutPage } from './Page_About.jsx';
export { default as ExploreTechPage } from './Page_ExploreTech.jsx';
export { default as ExploreProjectsPage } from './Page_ExploreProjects.jsx';
export { default as HomePage } from './Page_Home.jsx';
export { default as ProjectTemplatePage } from './Template_Project.jsx';
export { default as RequestQuotePage } from './Page_RequestQuote.jsx';
export { default as WhatToExpectPage } from './Page_WhatToExpect.jsx';
export { default as ContactFormPage } from './Page_Contact.jsx';
export { default as NeedWebsitePage } from './Page_NeedWebsite.jsx';
